name: 'Drift'
description: 'Documentation coverage and drift detection for TypeScript'
author: 'Ryan Waits'

branding:
  icon: 'file-text'
  color: 'green'

inputs:
  github-token:
    description: 'GitHub token for PR comments'
    required: false
    default: ${{ github.token }}
  working-directory:
    description: 'Working directory for the check'
    required: false
    default: '.'
  min-coverage:
    description: 'Minimum coverage percentage (0-100)'
    required: false
    default: '80'
  check-all:
    description: 'Check all packages, not just changed'
    required: false
    default: 'false'
  include-private:
    description: 'Include private packages'
    required: false
    default: 'false'
  anthropic-key:
    description: 'Anthropic API key for docs sync on merge (optional)'
    required: false
    default: ''
  docs-sync:
    description: 'Enable docs sync on merge'
    required: false
    default: 'true'

outputs:
  coverage:
    description: 'Current coverage percentage'
  health:
    description: 'Current health score'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install Drift CLI
      shell: bash
      run: bun install -g @driftdev/cli

    - name: Run drift ci
      if: github.event_name == 'pull_request'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        ARGS=""
        if [ "${{ inputs.check-all }}" = "true" ]; then
          ARGS="$ARGS --all"
        fi
        if [ "${{ inputs.include-private }}" = "true" ]; then
          ARGS="$ARGS --private"
        fi
        drift ci $ARGS

    - name: Docs sync on merge
      if: >
        github.event.pull_request.merged == true
        && inputs.docs-sync == 'true'
        && inputs.anthropic-key != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-key }}
      run: |
        cd $GITHUB_ACTION_PATH
        bun install
        bun run docs-sync.ts
