name: 'Drift'
description: 'Documentation coverage and drift detection for TypeScript'
author: 'Ryan Waits'

branding:
  icon: 'file-text'
  color: 'green'

inputs:
  github-token:
    description: 'GitHub token for PR comments'
    required: false
    default: ${{ github.token }}
  working-directory:
    description: 'Working directory for the check'
    required: false
    default: '.'
  min-coverage:
    description: 'Minimum coverage percentage (0-100)'
    required: false
    default: '80'
  check-all:
    description: 'Check all packages, not just changed'
    required: false
    default: 'false'
  include-private:
    description: 'Include private packages'
    required: false
    default: 'false'
  anthropic-key:
    description: 'Anthropic API key for docs sync on merge (optional)'
    required: false
    default: ''
  docs-pr:
    description: 'Create AI-generated PRs on remote docs repos on merge (requires anthropic-key)'
    required: false
    default: 'false'
  docs-issue:
    description: 'Create issues on remote docs repos for breaking changes (no AI needed)'
    required: false
    default: 'false'
  validate-examples:
    description: 'Type-check @example JSDoc blocks on PRs'
    required: false
    default: 'false'
  release-gate:
    description: 'Run drift release check on GitHub Release publish'
    required: false
    default: 'false'
  release-changelog:
    description: 'Append API changelog to GitHub Release body'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install Drift CLI
      shell: bash
      run: bun install -g @driftdev/cli

    - name: Run drift ci
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      id: drift_ci
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        ARGS=""
        if [ "${{ inputs.check-all }}" = "true" ]; then
          ARGS="$ARGS --all"
        fi
        if [ "${{ inputs.include-private }}" = "true" ]; then
          ARGS="$ARGS --private"
        fi
        drift ci $ARGS --min "${{ inputs.min-coverage }}"

    - name: Validate examples
      if: >
        github.event_name == 'pull_request'
        && github.event.action != 'closed'
        && inputs.validate-examples == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ARGS="--typecheck"
        if [ "${{ inputs.check-all }}" = "true" ]; then
          ARGS="$ARGS --all"
        fi
        if [ "${{ inputs.include-private }}" = "true" ]; then
          ARGS="$ARGS --private"
        fi
        drift examples $ARGS

    - name: Docs PR on merge
      if: >
        github.event.pull_request.merged == true
        && inputs.docs-pr == 'true'
        && inputs.anthropic-key != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-key }}
      run: |
        bun install --cwd $GITHUB_ACTION_PATH
        bun run $GITHUB_ACTION_PATH/docs-pr.ts

    - name: Docs issue on merge
      if: >
        github.event.pull_request.merged == true
        && inputs.docs-issue == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GH_TOKEN: ${{ inputs.github-token }}
      run: bun run $GITHUB_ACTION_PATH/docs-issue.ts

    - name: Release gate
      if: >
        github.event_name == 'release'
        && inputs.release-gate == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ARGS=""
        if [ "${{ inputs.check-all }}" = "true" ]; then
          ARGS="$ARGS --all"
        fi
        drift release $ARGS

    - name: Append API changelog to release
      if: >
        github.event_name == 'release'
        && inputs.release-changelog == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        TAG="${{ github.event.release.tag_name }}"
        PREV_TAG=$(git tag --sort=-v:refname | grep -A1 "^${TAG}$" | tail -1)
        if [ -z "$PREV_TAG" ] || [ "$PREV_TAG" = "$TAG" ]; then
          echo "No previous tag found, skipping changelog"
          exit 0
        fi
        CHANGELOG=$(drift changelog --base "$PREV_TAG" --format md 2>/dev/null || echo "")
        if [ -n "$CHANGELOG" ]; then
          EXISTING=$(gh release view "$TAG" --json body -q .body)
          gh release edit "$TAG" --notes "${EXISTING}

        ---

        ### API Changes (drift)

        ${CHANGELOG}"
        fi
