name: 'Drift'
description: 'Documentation coverage and drift detection for TypeScript'
author: 'Ryan Waits'

branding:
  icon: 'file-text'
  color: 'green'

inputs:
  package:
    description: 'Target package name (required for monorepos, e.g., "@myorg/core")'
    required: false
    default: ''
  min-coverage:
    description: 'Minimum coverage percentage (0-100)'
    required: false
    default: '80'
  min-health:
    description: 'Minimum health score (0-100), combines coverage + drift'
    required: false
    default: ''
  require-examples:
    description: 'Require @example blocks on all exports'
    required: false
    default: 'false'
  strict:
    description: |
      Fail conditions. Use preset name or comma-separated checks:
      Presets: ci (breaking,regression), release (all), quality (drift,undocumented)
      Custom: "breaking,drift,undocumented"
    required: false
    default: ''
  docs-glob:
    description: 'Glob pattern for markdown docs to check for impact (e.g., "docs/**/*.md")'
    required: false
    default: ''
  format:
    description: 'Output format for diff: text, json, github'
    required: false
    default: 'github'
  comment-on-pr:
    description: 'Post coverage report as PR comment'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for the check'
    required: false
    default: '.'
  skip-spec:
    description: 'Skip spec generation and use existing .drift/ files'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for PR comments'
    required: false
    default: ${{ github.token }}
  auto-commit-spec:
    description: 'Auto-commit .drift/ directory to the branch (PRs only)'
    required: false
    default: 'false'

outputs:
  coverage:
    description: 'Current coverage percentage'
  health:
    description: 'Current health score (coverage + drift penalty)'
  coverage-delta:
    description: 'Coverage change compared to base (on PRs)'
  drift-count:
    description: 'Number of drift issues detected'
  docs-impact-count:
    description: 'Number of docs files needing updates'
  spec-path:
    description: 'Path to generated drift.json'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Drift CLI
      shell: bash
      run: npm install -g @driftdev/cli

    - name: Resolve package name
      id: pkg
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -n "${{ inputs.package }}" ]; then
          PKG_NAME="${{ inputs.package }}"
        else
          # Read from package.json
          PKG_NAME=$(node -p "require('./package.json').name" 2>/dev/null || echo "unknown")
        fi
        echo "name=$PKG_NAME" >> $GITHUB_OUTPUT
        # Convert package name to path (handles scoped packages)
        echo "path=.drift/$PKG_NAME" >> $GITHUB_OUTPUT

    - name: Generate spec
      if: inputs.skip-spec != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        SPEC_ARGS=""
        if [ -n "${{ inputs.package }}" ]; then
          SPEC_ARGS="--package ${{ inputs.package }}"
        fi
        drift extract $SPEC_ARGS

    - name: Verify spec exists
      if: inputs.skip-spec == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        SPEC_PATH="${{ steps.pkg.outputs.path }}/drift.json"
        if [ ! -f "$SPEC_PATH" ]; then
          echo "Error: $SPEC_PATH not found. Either commit it or set skip-spec to false."
          exit 1
        fi

    - name: Check coverage
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ARGS=""
        if [ -n "${{ inputs.package }}" ]; then
          ARGS="$ARGS --package ${{ inputs.package }}"
        fi
        if [ -n "${{ inputs.min-health }}" ]; then
          ARGS="$ARGS --min-health ${{ inputs.min-health }}"
        else
          ARGS="$ARGS --min-coverage ${{ inputs.min-coverage }}"
        fi
        if [ "${{ inputs.require-examples }}" = "true" ]; then
          ARGS="$ARGS --examples presence"
        fi
        drift health $ARGS

    - name: Auto-commit spec (PRs only)
      if: github.event_name == 'pull_request' && inputs.auto-commit-spec == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        SPEC_DIR="${{ steps.pkg.outputs.path }}"
        if [ -d "$SPEC_DIR" ]; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$SPEC_DIR"
          if ! git diff --cached --quiet; then
            git commit -m "chore: update $SPEC_DIR [skip ci]"
            git push origin HEAD:${{ github.head_ref }}
          fi
        fi

    - name: Save head spec for diff
      if: github.event_name == 'pull_request'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        SPEC_PATH="${{ steps.pkg.outputs.path }}"
        if [ -f "$SPEC_PATH/openpkg.json" ]; then
          cp "$SPEC_PATH/openpkg.json" /tmp/openpkg-head.json
          cp "$SPEC_PATH/drift.json" /tmp/drift-head.json 2>/dev/null || true
        fi

    - name: Generate base spec (PRs only)
      if: github.event_name == 'pull_request'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        SPEC_PATH="${{ steps.pkg.outputs.path }}"
        git fetch origin ${{ github.base_ref }}
        git checkout FETCH_HEAD -- . 2>/dev/null || true

        if [ "${{ inputs.skip-spec }}" = "true" ] && [ -f "$SPEC_PATH/openpkg.json" ]; then
          cp "$SPEC_PATH/openpkg.json" /tmp/openpkg-base.json
          cp "$SPEC_PATH/drift.json" /tmp/drift-base.json 2>/dev/null || true
        else
          SPEC_ARGS=""
          if [ -n "${{ inputs.package }}" ]; then
            SPEC_ARGS="--package ${{ inputs.package }}"
          fi
          drift extract $SPEC_ARGS 2>/dev/null || true
          if [ -f "$SPEC_PATH/openpkg.json" ]; then
            cp "$SPEC_PATH/openpkg.json" /tmp/openpkg-base.json
            cp "$SPEC_PATH/drift.json" /tmp/drift-base.json 2>/dev/null || true
          else
            echo '{"openpkg":"0.4.0","exports":[]}' > /tmp/openpkg-base.json
          fi
        fi

        git checkout - -- . 2>/dev/null || true
        # Restore head spec
        if [ -f /tmp/openpkg-head.json ]; then
          mkdir -p "$SPEC_PATH"
          cp /tmp/openpkg-head.json "$SPEC_PATH/openpkg.json"
          cp /tmp/drift-head.json "$SPEC_PATH/drift.json" 2>/dev/null || true
        fi

    - name: Run diff (PRs only)
      if: github.event_name == 'pull_request'
      id: diff
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f /tmp/openpkg-base.json ] && [ -f /tmp/openpkg-head.json ]; then
          DIFF_ARGS="--format json"
          if [ -n "${{ inputs.docs-glob }}" ]; then
            DIFF_ARGS="$DIFF_ARGS --docs '${{ inputs.docs-glob }}'"
          fi
          DIFF=$(eval "drift diff /tmp/openpkg-base.json /tmp/openpkg-head.json $DIFF_ARGS")
          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Output GitHub annotations (PRs only)
      if: github.event_name == 'pull_request'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f /tmp/openpkg-base.json ] && [ -f /tmp/openpkg-head.json ]; then
          DIFF_ARGS="--format github"
          if [ -n "${{ inputs.docs-glob }}" ]; then
            DIFF_ARGS="$DIFF_ARGS --docs '${{ inputs.docs-glob }}'"
          fi
          eval "drift diff /tmp/openpkg-base.json /tmp/openpkg-head.json $DIFF_ARGS" || true
        fi

    - name: Check strict conditions
      if: github.event_name == 'pull_request' && inputs.strict != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f /tmp/openpkg-base.json ] && [ -f /tmp/openpkg-head.json ]; then
          DIFF_ARGS="--format text --strict '${{ inputs.strict }}'"
          if [ -n "${{ inputs.docs-glob }}" ]; then
            DIFF_ARGS="$DIFF_ARGS --docs '${{ inputs.docs-glob }}'"
          fi
          eval "drift diff /tmp/openpkg-base.json /tmp/openpkg-head.json $DIFF_ARGS"
        fi

    - name: Generate PR comment
      if: github.event_name == 'pull_request' && inputs.comment-on-pr == 'true'
      id: comment
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f /tmp/openpkg-base.json ] && [ -f /tmp/openpkg-head.json ]; then
          COMMENT_ARGS="--format pr-comment"
          COMMENT_ARGS="$COMMENT_ARGS --repo-url https://github.com/${{ github.repository }}"
          COMMENT_ARGS="$COMMENT_ARGS --sha ${{ github.event.pull_request.head.sha }}"
          COMMENT_ARGS="$COMMENT_ARGS --min-coverage ${{ inputs.min-coverage }}"
          if [ -n "${{ inputs.docs-glob }}" ]; then
            COMMENT_ARGS="$COMMENT_ARGS --docs '${{ inputs.docs-glob }}'"
          fi

          COMMENT=$(eval "drift diff /tmp/openpkg-base.json /tmp/openpkg-head.json $COMMENT_ARGS")
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Post PR comment
      if: github.event_name == 'pull_request' && inputs.comment-on-pr == 'true' && steps.comment.outputs.body != ''
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const body = process.env.COMMENT_BODY;

          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const existing = comments.find(c => c.body?.includes('Drift'));

          if (existing) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existing.id,
              body,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
          }
      env:
        COMMENT_BODY: ${{ steps.comment.outputs.body }}
